Repository PAHFIT/pahfit, pull requests merged in 2022-04, with the labels that each got.

#175 Improve Plot density
  pahfit/base.py
Labels: enhancement

#176 Implement Modified Blackbody
  pahfit/base.py
  pahfit/component_models.py
  pahfit/packs/scipack_ExGal_SpitzerIRSSLLL.ipac
Labels: bug

#177 Simple FWHM Fix
  pahfit/base.py
Labels: bug

#207 Update README.rst
  pahfit/data/README.rst
Labels: documentation
